
# BrieFlow configuration file

# Defining samples:
#   Samples must be defined in the following TSV files with columns:
#     sbs_samples.tsv: sample_fp, well, tile, cycle
#     phenotype_samples.tsv: sample_fp, well, tile

# Paths:
#   Paths are resolved relative to the directory the workflow is run from

# Parameters:
aggregate_process:
  cat_columns:
  - gene_symbol_0
  - sgRNA_0
  control_prefix: nontargeting
  feature_start: nucleus_dapi_mean
  group_columns:
  - well
  index_columns:
  - tile
  - cell_0
  population_feature: gene_symbol_0
  filter_single_gene: false
  threshold_conditions:
    nucleus_dapi_median:
    - 7
    - greater
  transformations_fp: config/transformations.tsv
all:
  root_fp: analysis_root/
phenotype_process:
  align: false
  cell_diameter: 54.126926685667364
  cellprob_threshold: 0
  channel_names:
  - DAPI
  - COXIV
  - CENPA
  - WGA
  cyto_index: 1
  cyto_model: cyto3
  dapi_index: 0
  flow_threshold: 0.4
  foci_channel: 2
  gpu: false
  mode: null
  nuclei_diameter: 40.96498163017951
preprocess:
  phenotype_channel_order: null
  phenotype_channel_order_flip: true
  phenotype_round_order: null
  phenotype_samples_fp: config/phenotype_samples.tsv
  sbs_channel_order: null
  sbs_channel_order_flip: true
  sbs_samples_fp: config/sbs_samples.tsv
sbs_process:
  alignment_method: DAPI
  bases:
  - G
  - T
  - A
  - C
  cell_diameter: 19.835095646937663
  cellprob_threshold: 0
  cyto_index: 4
  cyto_model: cyto3
  dapi_index: 0
  df_design_path: config/pool10_design.tsv
  flow_threshold: 0.4
  gpu: false
  keep_extras: false
  mode: null
  nuclei_diameter: 9.0270333367641
  q_min: 0
  segmentation_cycle_index: 10
  threshold_peaks: 400
